### ISSUE TITLE
RuntimeError: GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by Kerwin0621** [DepthAnything/Depth-Anything-V2#54]
python run.py --encoder vits --img-path assets/examples --outdir depth_vis
xFormers not available
xFormers not available
Progress 1/20: assets/examples/demo17.jpg
/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/conv.py:456: UserWarning: Attempt to open cnn_infer failed: handle=0 error: /home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/lib/../../nvidia/cudnn/lib/libcudnn_cnn_infer.so.8: undefined symbol: _Z22cudnnGenericOpTensorNdILi2EE13cudnnStatus_tP12cudnnContext16cudnnGenericOp_t21cudnnNanPropagation_tPK21cudnnActivationStructPKvPK17cudnnTensorStructS9_S9_SC_S9_S9_SC_Pv, version libcudnn_ops_infer.so.8 (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:81.)
  return F.conv2d(input, weight, bias, self.stride,
Traceback (most recent call last):
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/run.py", line 57, in <module>
    depth = depth_anything.infer_image(raw_image, args.input_size)
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/depth_anything_v2/dpt.py", line 190, in infer_image
    depth = self.forward(image)
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/depth_anything_v2/dpt.py", line 179, in forward
    features = self.pretrained.get_intermediate_layers(x, self.intermediate_layer_idx[self.encoder], return_class_token=True)
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/depth_anything_v2/dinov2.py", line 308, in get_intermediate_layers
    outputs = self._get_intermediate_layers_not_chunked(x, n)
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/depth_anything_v2/dinov2.py", line 272, in _get_intermediate_layers_not_chunked
    x = self.prepare_tokens_with_masks(x)
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/depth_anything_v2/dinov2.py", line 214, in prepare_tokens_with_masks
    x = self.patch_embed(x)
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/Documents/3D_Lane_Project/Depth-Anything-V2/depth_anything_v2/dinov2_layers/patch_embed.py", line 76, in forward
    x = self.proj(x)  # B C H W
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/xxx/miniconda3/envs/DPA_V2/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

similar issue as #15, but no specific solution proposed

**Comment by Kerwin0621** [comment]
The problem is solved.
Creat a python script. import torch, then print(f"cuDNN version: {torch.backends.cudnn.version()}").
By doing this, you can find the different version of the cudnn on your computer and the corrent version required.
Then update your cudnn in NVDIA web, then solved.
